ViewModels/FoodDetail.cs
using RealMenu.Models;

namespace RealMenu.ViewModels
{
    public class FoodDetail
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { set; get; }
        public string Ingredients { set; get; }
        public string ImageUrl { get; set; }
        public string Allergens { set; get; }
        public float MaxSize { set; get; }
        public float MinSize { set; get; }
        public string Price { set; get; }
        public string Spicy { set; get; }
        public string Vegetarian { set; get; }
        public int Weight { set; get; }
        public int FoodViewCount { set; get; }
    }
}

Controllers/UI/FoodPanel/FoodDetailsController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RealMenu.Data;
using RealMenu.ViewModels;

namespace RealMenu.Controllers
{
    public class FoodDetailsController : Controller
    {
        private ApiDBContext _dBContext;

        public FoodDetailsController(ApiDBContext dBContext)
        {
            _dBContext = dBContext;
        }

        [HttpGet]
        public IActionResult FoodInfo()
        {
            return View();
        }

        [HttpPost]
        public async Task<ViewResult> FoodInfo(int Id) 
        {
            FoodDetail foodDetail = new FoodDetail();
            var food = await _dBContext.Foods.FirstOrDefaultAsync(e => e.Id == Id);

            var foodViewCount = await _dBContext.FoodViews.Where(e => e.FoodId == Id).FirstOrDefaultAsync();
            foodDetail.Id = food.Id;
            foodDetail.ImageUrl = food.ImageUrl;
            foodDetail.Ingredients = food.Ingredients;
            foodDetail.MaxSize = food.MaxSize;
            foodDetail.MinSize = food.MinSize;
            foodDetail.Name = food.Name;
            foodDetail.Price = food.Price;
            foodDetail.Spicy = food.Spicy == 1 ? "true" : "false";
            foodDetail.Vegetarian = food.Vegetarian == 1 ? "true" : "false";
            foodDetail.Weight = food.Weight;
            foodDetail.Allergens = food.Allergens == 1 ? "true" : "false";
            foodDetail.Description = foodDetail.Description;
            foodDetail.FoodViewCount = ReferenceEquals(foodViewCount,null) ? 0 : foodViewCount.ViewCount;

            return View(foodDetail);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateFood(FoodDetail foodDetail) 
        {
            var food = await _dBContext.Foods.Where(e => e.Id == foodDetail.Id).FirstOrDefaultAsync();
            var Category = await _dBContext.Categories.Where(e => e.Id == food.CategoryId).FirstOrDefaultAsync();
            
            food.ImageUrl = foodDetail.ImageUrl;
            food.Ingredients = foodDetail.Ingredients;
            food.MaxSize = foodDetail.MaxSize;
            food.MinSize = foodDetail.MinSize;
            food.Name = foodDetail.Name;
            food.Price = foodDetail.Price;
            food.Spicy = !string.IsNullOrEmpty(foodDetail.Spicy) ? (byte)1 : (byte)0; ;
            food.Vegetarian = !string.IsNullOrEmpty(foodDetail.Vegetarian) ? (byte)1 : (byte)0;
            food.Weight = foodDetail.Weight;
            food.Allergens = !string.IsNullOrEmpty(foodDetail.Allergens) ? (byte)1 : (byte)0;
            food.Description = foodDetail.Description;
            await _dBContext.SaveChangesAsync(); 
            return RedirectToAction("GetRestaurantData", "Restaurant", new { @id = Category.RestaurantId });
        }
    }
}

Views/FoodDetails/FoodInfo.cshtml
@model RealMenu.ViewModels.FoodDetail;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="text-center">
    <h1>@Model.Name</h1>
</div>

<div class="container pb-5">
    <div>
        <div >
            <form class="form" asp-action="UpdateFood" asp-controller="FoodDetails" asp-anti-forgery="true" method="post">
                <input type="hidden" asp-for="Id" name="Id" value="@Model.Id" />
                <img class="img-thumbnail" src="@Model.ImageUrl" alt="@Model.Name" />
                <h5>Ссылка на картинку: <input type="text" asp-for="ImageUrl" name="ImageUrl" value="@Model.ImageUrl" /></h5>
                <h5>Еда: <input type="text" asp-for="Name" name="Name" value="@Model.Name" /></h5>
                <h5>Описание: <input type="text" asp-for="Description" name="Description" value="@Model.Description" /></h5>
                <h5>Цена: <input type="text" name="Price" value="@Model.Price" /></h5>
                <h5>Ингридиенты: <input type="text" asp-for="Ingredients" name="Ingredients" value="@Model.Ingredients" /></h5>
                <h5>Минимальный размер: <input type="text" asp-for="MaxSize" name="MaxSize" value="@Model.MaxSize" /></h5>
                <h5>Максимальный размер: <input type="text" asp-for="MinSize" name="MinSize" value="@Model.MinSize" /></h5>
                <h5>Острая: <input type="checkbox" name="Spicy" checked="@Model.Spicy == 1" /></h5>
                <h5>Аллергенны: <input type="checkbox" name="Allergens" checked="@Model.Allergens == 1"/> </h5>
                <h5>Вегетарианская: <input type="checkbox" name="Vegetarian" checked="@Model.Vegetarian == 1" /></h5>
                <h5>Вес еды: <input type="text" asp-for="Weight" name="Weight" value="@Model.Weight" /></h5>
                <div>
                    <input type="submit" class="btn btn-outline-info" value="Отредактировать" />
                </div>
            </form>
        </div>
    </div>
</div>